<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Adityas-MacBook-Pro.local" ignored="0" name="Default test" tests="5" failures="3" timestamp="27 Jan 2018 10:36:49 GMT" time="39.193" errors="0">
  <testcase name="VerifyFlightDetailsHeading" time="4.597" classname="com.expedia.adnatebeta.testrunner.NTRunnerTest">
    <failure type="java.lang.AssertionError" message="Flight Details expected:&amp;lt;Flight Details&amp;gt; but was:&amp;lt;Done&amp;gt;">
      <![CDATA[java.lang.AssertionError: Flight Details expected:<Flight Details> but was:<Done>at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)at com.expedia.adnatebeta.testrunner.NTRunnerTest.VerifyFlightDetailsHeading(NTRunnerTest.java:80)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- VerifyFlightDetailsHeading -->
  <testcase name="VerifyPageTitle" time="0.566" classname="com.expedia.adnatebeta.testrunner.NTRunnerTest">
    <skipped/>
  </testcase> <!-- VerifyPageTitle -->
  <testcase name="VerifyPageTitle" time="0.564" classname="com.expedia.adnatebeta.testrunner.NTRunnerTest">
    <skipped/>
  </testcase> <!-- VerifyPageTitle -->
  <testcase name="VerifyPageTitle" time="0.569" classname="com.expedia.adnatebeta.testrunner.NTRunnerTest">
    <failure type="java.lang.AssertionError" message="Welcome: Mercury Tours expected:&amp;lt;Welcome: Mercury Tours&amp;gt; but was:&amp;lt;Not Matching&amp;gt;">
      <![CDATA[java.lang.AssertionError: Welcome: Mercury Tours expected:<Welcome: Mercury Tours> but was:<Not Matching>at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)at com.expedia.adnatebeta.testrunner.NTRunnerTest.VerifyPageTitle(NTRunnerTest.java:60)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- VerifyPageTitle -->
  <testcase name="VerifyRegistrationProcess" time="5.906" classname="com.expedia.adnatebeta.testrunner.NTRunnerTest">
    <failure type="java.lang.AssertionError" message="Thank you for registering. You may now sign-in using the user name and password you&amp;apos;ve just entered. expected:&amp;lt;Thank you for registering. You may now sign-in using the user name and password you&amp;apos;ve just entered.&amp;gt; but was:&amp;lt;Enjoy&amp;gt;">
      <![CDATA[java.lang.AssertionError: Thank you for registering. You may now sign-in using the user name and password you've just entered. expected:<Thank you for registering. You may now sign-in using the user name and password you've just entered.> but was:<Enjoy>at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)at com.expedia.adnatebeta.testrunner.NTRunnerTest.VerifyRegistrationProcess(NTRunnerTest.java:114)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- VerifyRegistrationProcess -->
</testsuite> <!-- Default test -->
